[tool.poetry]
name = "stackexchange_django"
version = "0.1.0"
description = ""
authors = ["Kostas Kokkoros"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
psycopg2 = "*"
defusedxml = "*"
django-environ = "*"
djangorestframework = "*"
drf-spectacular = "*"
py7zr = "*"
requests = "*"
tqdm = "*"
pylint-django = "^2.5.2"
factory-boy = "^3.2.1"

[tool.poetry.dev-dependencies]
bandit = "*"
coverage = "*"
django-debug-toolbar = "*"
django-extensions = "*"
pylint = "*"
pylint-django = "*"
safety = "*"
Werkzeug = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
