[tool.poetry]
name = "stackexchange_django"
version = "0.1.0"
description = ""
authors = ["Kostas Kokkoros"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
psycopg2 = "^2.8.6"
django-environ = "^0.8.0"
djangorestframework = "^3.12.4"
drf-spectacular = "^0.21.0"
py7zr = "^0.17.0"
requests = "^2.25.1"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
django-debug-toolbar = "^3.2.1"
django-extensions = "^3.1.3"
safety = "^1.10.3"
Werkzeug = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
