"""Initial migration for the sites application
"""
# Generated by Django 5.1.9 on 2025-05-09 21:23

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    """The initial migration for the sites application.
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'schema_name',
                    models.CharField(
                        db_index=True, max_length=63, unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name]
                    ))
                ,
                ('name', models.CharField(help_text='The site name', max_length=32, unique=True)),
                ('description', models.CharField(help_text='The site description', max_length=64)),
                ('long_description', models.CharField(help_text='The site long description', max_length=128)),
                ('url', models.URLField(help_text='The site URL')),
                ('image_url', models.URLField(help_text='The site image URL')),
                ('icon_url', models.URLField(help_text='The site icon URL')),
                ('badge_icon_url', models.URLField(help_text='The site badge icon URL')),
                ('tag_css', models.TextField(help_text='CSS for tags')),
                ('tagline', models.CharField(help_text='The site tagline', max_length=256)),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='The site total question count')),
                ('total_answers', models.PositiveIntegerField(default=0, help_text='The site total answer count')),
                ('total_users', models.PositiveIntegerField(default=0, help_text='The site total user count')),
                ('total_comments', models.PositiveIntegerField(default=0, help_text='The site total comment count')),
                ('total_tags', models.PositiveIntegerField(default=0, help_text='The site total tag count')),
                ('last_post_date', models.DateTimeField(blank=True, help_text='The date of the last post', null=True)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True, help_text='The parent site', null=True, on_delete=django.db.models.deletion.CASCADE,
                        to='sites.site'
                    )
                ),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='sites.site'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
