# Generated by Django 4.2.9 on 2024-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='The user email', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='The user name', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='The user email', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'site_users',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The site name', max_length=255, unique=True)),
                ('cache_key', models.CharField(help_text='The cache key for the site data')),
            ],
            options={
                'db_table': 'sites',
                'unique_together': {('name', 'cache_key')},
            },
        ),
    ]
